CREATE DATABASE OPTURISMO;

CREATE TABLE PREST_SERVICO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NULL,
  TEL_CELULAR VARCHAR(20) NULL,
  TELEFONE VARCHAR(20) NULL,
  CNPJ VARCHAR(30) NULL,
  EMAIL VARCHAR(70) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE OP_TRANSPORTE (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NULL,
  TRAJETO VARCHAR NULL,
  NUM_ACENTOS INTEGER UNSIGNED NULL,
  NUM_ACENTOS_DISP INTEGER UNSIGNED NULL,
  INF_RESTRICOES VARCHAR NULL,
  TAXA_ADD_EMBARQUE FLOAT NULL,
  NUM_ACENTOS_MIN INTEGER UNSIGNED NULL,
  TIPO CHAR(1) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE QUARTOS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(30) NULL,
  QTD_CAMAS_CASAL INTEGER UNSIGNED NULL,
  QTD_CAMAS_SOLTEIRO INTEGER UNSIGNED NULL,
  NUMERO INTEGER UNSIGNED NULL,
  ANDAR INTEGER UNSIGNED NULL,
  VALOR FLOAT NULL,
  OBS VARCHAR(100) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(20) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE SERVICOS (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NULL,
  DESCRICAO VARCHAR NULL,
  VALOR FLOAT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE FORMAPGTO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICA VARCHAR(20) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(40) NULL,
  SOBRENOME VARCHAR(40) NULL,
  RG VARCHAR(20) NULL,
  CPF VARCHAR(20) NULL,
  DT_NASCIMENTO DATE NULL,
  EMAIL VARCHAR(70) NULL,
  TEL_CELULAR VARCHAR(20) NULL,
  TEL_RESIDENCIAL VARCHAR(20) NULL,
  TEL_TRABALHO VARCHAR(20) NULL,
  ESTADO_CIVIL VARCHAR(20) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE HOTEL (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NULL,
  END_RUA VARCHAR(30) NULL,
  END_NUMERO INTEGER UNSIGNED NULL,
  END_BAIRRO VARCHAR(30) NULL,
  END_CIDADE VARCHAR(30) NULL,
  END_UF VARCHAR(5) NULL,
  END_PAIS VARCHAR(30) NULL,
  NUM_QUARTOS INTEGER UNSIGNED NULL,
  CLASSIFIC_EMBRA INTEGER UNSIGNED NULL,
  ALIMENTACAO CHAR(1) NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE FINANCEIRO (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FORMAPGTO_ID INTEGER UNSIGNED NOT NULL,
  VALOR_TOTAL FLOAT NULL,
  VALOR_ADD FLOAT NULL,
  VALOR_DESC FLOAT NULL,
  DT_FINANCEIRO DATE NULL,
  DT_VENCIMENTO DATE NULL,
  PRIMARY KEY(ID),
  INDEX FINANCEIRO_FKIndex1(FORMAPGTO_ID),
  FOREIGN KEY(FORMAPGTO_ID)
    REFERENCES FORMAPGTO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PACOTES (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(40) NULL,
  DT_INICIAL DATE NULL,
  DT_FINAL INTEGER UNSIGNED NULL,
  HOTEL_ID INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX PACOTES_FKIndex1(HOTEL_ID),
  FOREIGN KEY(HOTEL_ID)
    REFERENCES HOTEL(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE HOTEL_QUARTOS (
  HOTEL_ID INTEGER UNSIGNED NOT NULL,
  QUARTOS_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(HOTEL_ID, QUARTOS_ID),
  INDEX HOTEL_QUARTOS_FKIndex1(HOTEL_ID),
  FOREIGN KEY(HOTEL_ID)
    REFERENCES HOTEL(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(QUARTOS_ID)
    REFERENCES QUARTOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PREST_SERVICO_SERVICOS (
  PREST_SERVICO_ID INTEGER UNSIGNED NOT NULL,
  SERVICOS_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(PREST_SERVICO_ID, SERVICOS_ID),
  INDEX PREST_SERVICO_SERVICOS_FKIndex1(PREST_SERVICO_ID),
  INDEX PREST_SERVICO_SERVICOS_FKIndex2(SERVICOS_ID),
  FOREIGN KEY(PREST_SERVICO_ID)
    REFERENCES PREST_SERVICO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SERVICOS_ID)
    REFERENCES SERVICOS(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SERVICOS_PACOTES (
  PREST_SERVICO_SERVICOS_SERVICOS_ID INTEGER UNSIGNED NOT NULL,
  PREST_SERVICO_SERVICOS_PREST_SERVICO_ID INTEGER UNSIGNED NOT NULL,
  OP_TRANSPORTE_ID INTEGER UNSIGNED NULL,
  INDEX SERVICOS_PACOTES_FKIndex4(OP_TRANSPORTE_ID),
  FOREIGN KEY(PACOTES_ID)
    REFERENCES PACOTES(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(OP_TRANSPORTE_ID)
    REFERENCES OP_TRANSPORTE(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PREST_SERVICO_SERVICOS_PREST_SERVICO_ID, PREST_SERVICO_SERVICOS_SERVICOS_ID)
    REFERENCES PREST_SERVICO_SERVICOS(PREST_SERVICO_ID, SERVICOS_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE RESERVA (
  ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USUARIO_ID INTEGER UNSIGNED NOT NULL,
  PACOTES_ID INTEGER UNSIGNED NOT NULL,
  CLIENTE_ID INTEGER UNSIGNED NOT NULL,
  DT_RESERVA DATE NULL,
  PERIODO_INI DATE NULL,
  PERIODO_FINAL DATE NULL,
  SITUACAO CHAR(1) NOT NULL,
  NRO_PESSOAS INTEGER UNSIGNED NULL,
  PRIMARY KEY(ID),
  INDEX RESERVA_FKIndex1(CLIENTE_ID),
  INDEX RESERVA_FKIndex2(PACOTES_ID),
  INDEX RESERVA_FKIndex3(USUARIO_ID),
  FOREIGN KEY(CLIENTE_ID)
    REFERENCES CLIENTE(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PACOTES_ID)
    REFERENCES PACOTES(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(USUARIO_ID)
    REFERENCES USUARIO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE RESERVA_FINANCEIRO (
  RESERVA_ID INTEGER UNSIGNED NOT NULL,
  FINANCEIRO_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(RESERVA_ID, FINANCEIRO_ID),
  INDEX RESERVA_FINANCEIRO_FKIndex1(RESERVA_ID),
  INDEX RESERVA_FINANCEIRO_FKIndex2(FINANCEIRO_ID),
  FOREIGN KEY(RESERVA_ID)
    REFERENCES RESERVA(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(FINANCEIRO_ID)
    REFERENCES FINANCEIRO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


